# Generated by Django 5.0.8 on 2024-10-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='gamers.team', verbose_name='teams'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('year', 'group', 'group_index')},
        ),
    ]
