# Generated by Django 5.0.8 on 2024-10-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='game',
            name='connoisseur_score',
            field=models.PositiveIntegerField(default=0, verbose_name='connoisseur score'),
        ),
        migrations.AddField(
            model_name='game',
            name='tv_viewers_score',
            field=models.PositiveIntegerField(default=0, verbose_name='tv viewers score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='group_index',
            field=models.PositiveIntegerField(default=1, verbose_name='game index'),
        ),
        migrations.AlterField(
            model_name='game',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.group', verbose_name='group'),
        ),
    ]
