# Generated by Django 5.0.8 on 2024-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_group_alter_game_options_game_connoisseur_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(choices=[('first_game', 'First game'), ('second_game', 'Second game'), ('third_game', 'Third game'), ('fourth_game', 'Fourth game'), ('fifth_game', 'Fifth game'), ('final_game', 'Final game'), ('year_finale', 'Year finale')], default=None, verbose_name='game name'),
            preserve_default=False,
        ),
    ]
