# Generated by Django 5.0.8 on 2024-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='full_name',
            field=models.CharField(default=None, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
