# Generated by Django 5.0.8 on 2024-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='codename',
            field=models.CharField(default=None, primary_key=True, serialize=False, verbose_name='codename'),
            preserve_default=False,
        ),
    ]
