# Generated by Django 5.0.8 on 2024-10-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_group_id_group_codename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('year', 'group_index')},
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
    ]
