# Generated by Django 5.0.8 on 2024-10-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_unique_together_remove_game_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.group', verbose_name='group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('year', 'group', 'group_index')},
        ),
    ]
