# Generated by Django 5.0.8 on 2024-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_season_alter_game_unique_together_game_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='connoisseurs_stat',
            field=models.PositiveIntegerField(default=0, verbose_name='connoisseurs stat'),
        ),
        migrations.AddField(
            model_name='season',
            name='tv_viewers_stat',
            field=models.PositiveIntegerField(default=0, verbose_name='TV viewers stat'),
        ),
    ]
