# Generated by Django 5.0.8 on 2024-10-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_season_connoisseurs_stat_season_tv_viewers_stat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('group', 'group_index')},
        ),
        migrations.AddField(
            model_name='group',
            name='season',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='game.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.group', verbose_name='group'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
    ]
