# Generated by Django 5.0.8 on 2024-10-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_game_unique_together_group_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='connoisseur_score',
        ),
        migrations.AddField(
            model_name='game',
            name='connoisseurs_score',
            field=models.PositiveIntegerField(default=0, verbose_name='connoisseurs score'),
        ),
    ]
