# Generated by Django 5.0.8 on 2024-10-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_game_connoisseur_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='full_name_en',
            field=models.CharField(null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='game',
            name='full_name_ru',
            field=models.CharField(null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='season',
            name='rules_en',
            field=models.TextField(null=True, verbose_name='rules'),
        ),
        migrations.AddField(
            model_name='season',
            name='rules_ru',
            field=models.TextField(null=True, verbose_name='rules'),
        ),
    ]
