# Generated by Django 5.0.8 on 2024-10-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_full_name_en_game_full_name_ru_group_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('group_index',)},
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
    ]
