# Generated by Django 5.0.8 on 2024-10-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_group_id_alter_group_codename_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.group', verbose_name='group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('group', 'group_index')},
        ),
    ]
