# Generated by Django 5.0.8 on 2024-10-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_group_season'),
        ('gamers', '0007_alter_baseplayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gamers.connoisseur', verbose_name='best player'),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(default='Joint', verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='location_en',
            field=models.CharField(null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='game',
            name='location_ru',
            field=models.CharField(null=True, verbose_name='location'),
        ),
    ]
