# Generated by Django 5.0.8 on 2024-10-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game_best_player_game_location_game_location_en_and_more'),
        ('gamers', '0007_alter_baseplayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prize_type',
            field=models.CharField(blank=True, null=True, verbose_name='prize type'),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_type_en',
            field=models.CharField(blank=True, null=True, verbose_name='prize type'),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_type_ru',
            field=models.CharField(blank=True, null=True, verbose_name='prize type'),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prize_winners', to='gamers.connoisseur', verbose_name='prize winner'),
        ),
        migrations.AlterField(
            model_name='game',
            name='best_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_players', to='gamers.connoisseur', verbose_name='best player'),
        ),
    ]
