# Generated by Django 5.0.8 on 2024-10-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_game_prize_type_game_prize_type_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['group_index'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
    ]
