# Generated by Django 5.0.8 on 2024-10-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_index',
            field=models.PositiveIntegerField(default=0, verbose_name='group index'),
            preserve_default=False,
        ),
    ]
