# Generated by Django 5.0.8 on 2024-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_telegram_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
