# Generated by Django 5.0.8 on 2024-10-24 14:07

import auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/img/no_photo.jpg', upload_to=auth.models.user_pic_path, verbose_name='avatar'),
        ),
    ]
