# Generated by Django 5.0.8 on 2024-10-24 15:02

import auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/no_photo.jpg', upload_to=auth.models.user_pic_path, verbose_name='avatar'),
        ),
    ]
