# Generated by Django 5.0.8 on 2024-10-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_group_alter_game_options_game_connoisseur_score_and_more'),
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Award', 'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='connoisseur',
            options={'verbose_name': 'Connoisseur', 'verbose_name_plural': 'Connoisseurs'},
        ),
        migrations.AlterModelOptions(
            name='tvviewer',
            options={'verbose_name': 'TV Viewer', 'verbose_name_plural': 'TV Viewers'},
        ),
        migrations.AddField(
            model_name='award',
            name='pic',
            field=models.ImageField(default='no_photo.jpg', upload_to='awards/'),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='captains', to='gamers.connoisseur', verbose_name='captain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseplayer',
            name='awards',
            field=models.ManyToManyField(blank=True, to='gamers.award', verbose_name='awards'),
        ),
        migrations.AlterField(
            model_name='connoisseur',
            name='first_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.game', verbose_name='first game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.game', verbose_name='first game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='gamers.connoisseur', verbose_name='players'),
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
    ]
