# Generated by Django 5.0.8 on 2024-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0003_rename_name_award_codename_baseplayer_about_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='name',
            field=models.CharField(default='award', verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='codename',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='codename'),
        ),
    ]
